#!/bin/sh

exit_if_missing() {
    which $1
    if [ $? -ne 0 ]; then
        echo "ERROR: '$1' was not found in \$PATH. Install $1 v$2 and then rerun this script."
        exit $?
    fi
}

run() {
    local out=`$1`
    if [ $? -eq 0 ]; then
        echo "OK: $1"
    else
        echo "ERROR: $out"
    fi
}

recommended_ruby=`cat .ruby-version`
recommended_node=`cat .nvmrc`
exit_if_missing "ruby" $recommended_ruby
exit_if_missing "node" $recommended_node
exit_if_missing "bundle" "<any version>"
exit_if_missing "npm" "<any version>"

run "bundle install"
run "npm install"
echo "DONE!"
